Update Elixir and Erlang versions
rentpath/ex_json_logger pull request #22
Opened 2023-01-06 15:53 UTC by joshdayan

[Card](https://rentpath.atlassian.net/browse/SRV-3789)

2023-01-06 16:00 UTC, Stratus3D commented on .github/workflows/elixir.yml
> +            elixir: '1.14'
My guess is the new version of credo may not work on Elixir 1.12, so we may have to only support 1.13 and 1.14, with OTP 24 and 25, and maybe 23.

2023-01-06 16:01 UTC, Stratus3D requested changes
Workflow versions don't match version range specified in mix.exs file

2023-01-10 13:52 UTC, joshdayan commented on .github/workflows/elixir.yml
> +            elixir: '1.14'
Due to a hard deprecation in `Elixir@1.13` https://github.com/elixir-lang/elixir/blob/v1.13/CHANGELOG.md we cannot support 1.12 anymore.

2023-01-10 13:57 UTC, Stratus3D approved these changes

2023-01-10 13:58 UTC, merged